import { useRef } from 'react';
import { motion } from 'framer-motion';

export default function AIVideos() {
    const videoUrl = '/video/ai_video.mp4';
    const videoRef = useRef(null);

    const handleFullscreen = () => {
        if (!videoRef.current) return;
        if (videoRef.current.requestFullscreen) {
            videoRef.current.requestFullscreen();
        } else if (videoRef.current.webkitRequestFullscreen) { /* Safari */
            videoRef.current.webkitRequestFullscreen();
        } else if (videoRef.current.msRequestFullscreen) { /* IE11 */
            videoRef.current.msRequestFullscreen();
        }
    };

    return (
        <div className="min-h-screen bg-[#050508] text-foreground pt-24 px-4 md:px-8 pb-16 flex flex-col items-center justify-center relative overflow-hidden">
            
            {/* Cinematic background light spill */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[70vw] h-[50vh] bg-indigo-500/10 blur-[140px] rounded-full pointer-events-none" />
            
            {/* Soft grid overlay */}
            <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iMSIgY3k9IjEiIHI9IjEiIGZpbGw9InJnYmEoMjU1LDI1NSwyNTUsMC4wMykiLz48L3N2Zz4=')] [mask-image:radial-gradient(ellipse_60%_60%_at_50%_50%,#000_10%,transparent_100%)] pointer-events-none" />

            <div className="w-full max-w-6xl relative z-10 flex flex-col items-center">
                
                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="w-full mb-8 flex flex-col sm:flex-row items-center justify-between gap-4"
                >
                    <div>
                        <h1 className="text-xl md:text-5xl font-black tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-white via-white/90 to-white/50 mb-2">
                            AI Videos
                        </h1>
                        <p className="text-sm text-white/40 tracking-wider uppercase font-medium">
                            Synthesized Media Platform
                        </p>
                    </div>
                </motion.div>

                {/* Main Video Frame */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.96 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: 0.1, duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                    className="relative w-full aspect-video rounded-2xl md:rounded-[2rem] bg-[#000] overflow-hidden border border-white/[0.08] shadow-[0_20px_60px_-15px_rgba(0,0,0,0.8),0_0_80px_rgba(99,102,241,0.1)] group ring-1 ring-white/5"
                >
                    {/* Inner highlight line at top of frame for 3D realism */}
                    <div className="absolute inset-x-0 top-0 h-[1px] bg-gradient-to-r from-transparent via-white/15 to-transparent pointer-events-none z-20" />

                    <video
                        ref={videoRef}
                        className="w-full h-full object-contain focus:outline-none"
                        controls
                        playsInline
                        preload="metadata"
                        src={videoUrl}
                        poster="/video/poster_placeholder.png" // Added optional fallback logic
                    >
                        Your browser does not support the video tag.
                    </video>
                </motion.div>
                
                {/* Details Footer */}
                <motion.div 
                    initial={{ opacity: 0, y: 15 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.25 }}
                    className="mt-8 flex items-center justify-between w-full px-2"
                >
                    {/* <div className="flex flex-col gap-1.5">
                        <div className="flex items-center gap-3">
                            <span className="text-white/90 font-semibold text-xl tracking-tight">ai_video.mp4</span>
                            <span className="px-2 py-0.5 bg-indigo-500/20 text-indigo-300 text-[10px] font-bold uppercase tracking-wider rounded border border-indigo-500/30">
                                4K AI GEN
                            </span>
                        </div>
                        <span className="text-white/40 text-sm">Generated by high-fidelity text-to-video dynamics engine.</span>
                    </div> */}

                    {/* Fake action buttons for styling completeness */}
                    {/* <div className="flex items-center gap-2 hidden sm:flex">
                        <button className="w-10 h-10 rounded-full bg-white/5 border border-white/5 hover:bg-white/10 flex items-center justify-center text-white/60 hover:text-white transition-colors">
                            <svg width={18} height={18} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                            </svg>
                        </button>
                        <button className="w-10 h-10 rounded-full bg-white/5 border border-white/5 hover:bg-white/10 flex items-center justify-center text-white/60 hover:text-white transition-colors">
                            <svg width={18} height={18} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z" />
                            </svg>
                        </button>
                    </div> */}
                </motion.div>

            </div>
        </div>
    );
}
